Feature/strip sentence frags
moirairpg/moirai pull request #91
Opened 2023-03-22 12:34 UTC by MagicShel

2023-03-23 20:12 UTC, thaalesalves requested changes

2023-03-23 20:12 UTC, thaalesalves commented on src/main/java/es/thalesalv/chatrpg/application/service/completion/ChatCompletionService.java
> +        outputProcessor.addRule(s -> Pattern.compile("(?<=[.!?\\n])\"?[^.!?\\n]*(?![.!?\\n])$", Pattern.DOTALL & Pattern.MULTILINE).matcher(s).replaceAll(StringUtils.EMPTY));
What exactly is happening here?

2023-03-24 12:25 UTC, MagicShel commented on src/main/java/es/thalesalv/chatrpg/application/service/completion/ChatCompletionService.java
> +        outputProcessor.addRule(s -> Pattern.compile("(?<=[.!?\\n])\"?[^.!?\\n]*(?![.!?\\n])$", Pattern.DOTALL & Pattern.MULTILINE).matcher(s).replaceAll(StringUtils.EMPTY));
Select all characters between the last newline or end-of-sentence punctuation and the end of a non-terminated sentence and replace them with nothing.

Or, more plainly, it removes any dangling sentence fragment off the end of a generation.

2023-03-25 21:08 UTC, thaalesalves approved these changes

2023-03-25 21:09 UTC, merged